name: Build

on:
  push:
    branches: [ 3.8-m ]

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup node.js
        uses: actions/setup-node@v1
      - name: Install typescript
        run: npm install -g typescript
      - name: Build everything
        run: |
          Get-ChildItem .\tsconfig.*json | 
          ForEach-Object { tsc -p $_.FullName }
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build

