name: Publish

on:
  push:
    branches: [ 3.8-m ]
    tags: [ 'v*' ]

defaults:
  run:
    shell: pwsh

jobs:
  core:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Checkout spine-core
        uses: actions/checkout@v2
        with:
          repository: 'GourmetEdifice/spine-core'
          path: './spine-core'
          token: ${{ secrets.SPINE_GUILD_TOKEN }}
      - name: Setup node.js
        uses: actions/setup-node@v1
      - name: Install typescript
        run: npm install -g typescript
      - name: Build core
        run: |
          tsc -p ./tsconfig.core.json --outfile ./spine-core/lib/spine-core.js
      - name: Push files
        run: |
          pushd spine-core
          git add lib
          git config user.name 'KiruyaMomochi'
          git config user.email 'KiruyaMomochi@users.noreply.github.com'
          git commit -m ${{ github.ref }}
          git push
          popd
